//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctApproach complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctApproach">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApproachLegs" type="{}ctApproachLegs" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MissedApproachLegs" type="{}ctApproachLegs" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Transition" type="{}ctTransition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{}stApproachType" />
 *       &lt;attribute name="runway" type="{}stRunwayNumber" />
 *       &lt;attribute name="designator" type="{}stDesignator" />
 *       &lt;attribute name="suffix" type="{}stCharacter" />
 *       &lt;attribute name="gpsOverlay" type="{}stBool" />
 *       &lt;attribute name="fixType" use="required" type="{}stFixType" />
 *       &lt;attribute name="fixRegion" use="required" type="{}stString2" />
 *       &lt;attribute name="fixIdent" use="required" type="{}stString5" />
 *       &lt;attribute name="altitude" use="required" type="{}stAltitude" />
 *       &lt;attribute name="heading" use="required" type="{}stHeading" />
 *       &lt;attribute name="missedAltitude" use="required" type="{}stAltitude" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctApproach", propOrder = {
    "approachLegs",
    "missedApproachLegs",
    "transition"
})
public class CtApproach {

    @XmlElement(name = "ApproachLegs")
    protected List<CtApproachLegs> approachLegs;
    @XmlElement(name = "MissedApproachLegs")
    protected List<CtApproachLegs> missedApproachLegs;
    @XmlElement(name = "Transition")
    protected List<CtTransition> transition;
    @XmlAttribute(name = "type", required = true)
    protected StApproachType type;
    @XmlAttribute(name = "runway")
    protected String runway;
    @XmlAttribute(name = "designator")
    protected StDesignator designator;
    @XmlAttribute(name = "suffix")
    protected String suffix;
    @XmlAttribute(name = "gpsOverlay")
    protected StBool gpsOverlay;
    @XmlAttribute(name = "fixType", required = true)
    protected StFixType fixType;
    @XmlAttribute(name = "fixRegion", required = true)
    protected String fixRegion;
    @XmlAttribute(name = "fixIdent", required = true)
    protected String fixIdent;
    @XmlAttribute(name = "altitude", required = true)
    protected String altitude;
    @XmlAttribute(name = "heading", required = true)
    protected double heading;
    @XmlAttribute(name = "missedAltitude", required = true)
    protected String missedAltitude;

    /**
     * Gets the value of the approachLegs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the approachLegs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApproachLegs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtApproachLegs }
     * 
     * 
     */
    public List<CtApproachLegs> getApproachLegs() {
        if (approachLegs == null) {
            approachLegs = new ArrayList<CtApproachLegs>();
        }
        return this.approachLegs;
    }

    /**
     * Gets the value of the missedApproachLegs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the missedApproachLegs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMissedApproachLegs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtApproachLegs }
     * 
     * 
     */
    public List<CtApproachLegs> getMissedApproachLegs() {
        if (missedApproachLegs == null) {
            missedApproachLegs = new ArrayList<CtApproachLegs>();
        }
        return this.missedApproachLegs;
    }

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtTransition }
     * 
     * 
     */
    public List<CtTransition> getTransition() {
        if (transition == null) {
            transition = new ArrayList<CtTransition>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link StApproachType }
     *     
     */
    public StApproachType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link StApproachType }
     *     
     */
    public void setType(StApproachType value) {
        this.type = value;
    }

    /**
     * Gets the value of the runway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunway() {
        return runway;
    }

    /**
     * Sets the value of the runway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunway(String value) {
        this.runway = value;
    }

    /**
     * Gets the value of the designator property.
     * 
     * @return
     *     possible object is
     *     {@link StDesignator }
     *     
     */
    public StDesignator getDesignator() {
        return designator;
    }

    /**
     * Sets the value of the designator property.
     * 
     * @param value
     *     allowed object is
     *     {@link StDesignator }
     *     
     */
    public void setDesignator(StDesignator value) {
        this.designator = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the gpsOverlay property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getGpsOverlay() {
        return gpsOverlay;
    }

    /**
     * Sets the value of the gpsOverlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setGpsOverlay(StBool value) {
        this.gpsOverlay = value;
    }

    /**
     * Gets the value of the fixType property.
     * 
     * @return
     *     possible object is
     *     {@link StFixType }
     *     
     */
    public StFixType getFixType() {
        return fixType;
    }

    /**
     * Sets the value of the fixType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StFixType }
     *     
     */
    public void setFixType(StFixType value) {
        this.fixType = value;
    }

    /**
     * Gets the value of the fixRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixRegion() {
        return fixRegion;
    }

    /**
     * Sets the value of the fixRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixRegion(String value) {
        this.fixRegion = value;
    }

    /**
     * Gets the value of the fixIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixIdent() {
        return fixIdent;
    }

    /**
     * Sets the value of the fixIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixIdent(String value) {
        this.fixIdent = value;
    }

    /**
     * Gets the value of the altitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltitude(String value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the heading property.
     * 
     */
    public double getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     */
    public void setHeading(double value) {
        this.heading = value;
    }

    /**
     * Gets the value of the missedAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissedAltitude() {
        return missedAltitude;
    }

    /**
     * Sets the value of the missedAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissedAltitude(String value) {
        this.missedAltitude = value;
    }

}
