//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctBoundary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctBoundary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}grpBoundaryChildren" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{}stBoundaryType" />
 *       &lt;attribute name="name" type="{}stString48" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctBoundary", propOrder = {
    "grpBoundaryChildren"
})
public class CtBoundary {

    @XmlElementRefs({
        @XmlElementRef(name = "Line", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Origin", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Circle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Com", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BoundaryStart", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Arc", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> grpBoundaryChildren;
    @XmlAttribute(name = "type")
    protected StBoundaryType type;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the grpBoundaryChildren property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grpBoundaryChildren property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrpBoundaryChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CtCom }{@code >}
     * {@link JAXBElement }{@code <}{@link CtStartBoundary }{@code >}
     * {@link JAXBElement }{@code <}{@link CtVertexLL }{@code >}
     * {@link JAXBElement }{@code <}{@link CtVertexLL }{@code >}
     * {@link JAXBElement }{@code <}{@link CtArc }{@code >}
     * {@link JAXBElement }{@code <}{@link CtCircle }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getGrpBoundaryChildren() {
        if (grpBoundaryChildren == null) {
            grpBoundaryChildren = new ArrayList<JAXBElement<?>>();
        }
        return this.grpBoundaryChildren;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link StBoundaryType }
     *     
     */
    public StBoundaryType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBoundaryType }
     *     
     */
    public void setType(StBoundaryType value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
