//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctColor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctColor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctColor")
public class CtColor {

    @XmlAttribute(name = "red")
    @XmlSchemaType(name = "unsignedByte")
    protected Short red;
    @XmlAttribute(name = "green")
    @XmlSchemaType(name = "unsignedByte")
    protected Short green;
    @XmlAttribute(name = "blue")
    @XmlSchemaType(name = "unsignedByte")
    protected Short blue;

    /**
     * Gets the value of the red property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRed() {
        return red;
    }

    /**
     * Sets the value of the red property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRed(Short value) {
        this.red = value;
    }

    /**
     * Gets the value of the green property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getGreen() {
        return green;
    }

    /**
     * Sets the value of the green property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setGreen(Short value) {
        this.green = value;
    }

    /**
     * Gets the value of the blue property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getBlue() {
        return blue;
    }

    /**
     * Sets the value of the blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setBlue(Short value) {
        this.blue = value;
    }

}
