//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctDeleteNavigation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctDeleteNavigation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="deleteAllWaypoints" type="{}stBool" />
 *       &lt;attribute name="deleteAllVORs" type="{}stBool" />
 *       &lt;attribute name="deleteAllNDBs" type="{}stBool" />
 *       &lt;attribute name="deleteAllTerminalWaypoints" type="{}stBool" />
 *       &lt;attribute name="deleteAllTerminalNDBs" type="{}stBool" />
 *       &lt;attribute name="deleteAllILSs" type="{}stBool" />
 *       &lt;attribute name="deleteAllApproaches" type="{}stBool" />
 *       &lt;attribute name="deleteAllDepartures" type="{}stBool" />
 *       &lt;attribute name="deleteAllArrivals" type="{}stBool" />
 *       &lt;attribute name="deleteAllFrequencies" type="{}stBool" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctDeleteNavigation")
public class CtDeleteNavigation {

    @XmlAttribute(name = "deleteAllWaypoints")
    protected StBool deleteAllWaypoints;
    @XmlAttribute(name = "deleteAllVORs")
    protected StBool deleteAllVORs;
    @XmlAttribute(name = "deleteAllNDBs")
    protected StBool deleteAllNDBs;
    @XmlAttribute(name = "deleteAllTerminalWaypoints")
    protected StBool deleteAllTerminalWaypoints;
    @XmlAttribute(name = "deleteAllTerminalNDBs")
    protected StBool deleteAllTerminalNDBs;
    @XmlAttribute(name = "deleteAllILSs")
    protected StBool deleteAllILSs;
    @XmlAttribute(name = "deleteAllApproaches")
    protected StBool deleteAllApproaches;
    @XmlAttribute(name = "deleteAllDepartures")
    protected StBool deleteAllDepartures;
    @XmlAttribute(name = "deleteAllArrivals")
    protected StBool deleteAllArrivals;
    @XmlAttribute(name = "deleteAllFrequencies")
    protected StBool deleteAllFrequencies;

    /**
     * Gets the value of the deleteAllWaypoints property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllWaypoints() {
        return deleteAllWaypoints;
    }

    /**
     * Sets the value of the deleteAllWaypoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllWaypoints(StBool value) {
        this.deleteAllWaypoints = value;
    }

    /**
     * Gets the value of the deleteAllVORs property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllVORs() {
        return deleteAllVORs;
    }

    /**
     * Sets the value of the deleteAllVORs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllVORs(StBool value) {
        this.deleteAllVORs = value;
    }

    /**
     * Gets the value of the deleteAllNDBs property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllNDBs() {
        return deleteAllNDBs;
    }

    /**
     * Sets the value of the deleteAllNDBs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllNDBs(StBool value) {
        this.deleteAllNDBs = value;
    }

    /**
     * Gets the value of the deleteAllTerminalWaypoints property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllTerminalWaypoints() {
        return deleteAllTerminalWaypoints;
    }

    /**
     * Sets the value of the deleteAllTerminalWaypoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllTerminalWaypoints(StBool value) {
        this.deleteAllTerminalWaypoints = value;
    }

    /**
     * Gets the value of the deleteAllTerminalNDBs property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllTerminalNDBs() {
        return deleteAllTerminalNDBs;
    }

    /**
     * Sets the value of the deleteAllTerminalNDBs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllTerminalNDBs(StBool value) {
        this.deleteAllTerminalNDBs = value;
    }

    /**
     * Gets the value of the deleteAllILSs property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllILSs() {
        return deleteAllILSs;
    }

    /**
     * Sets the value of the deleteAllILSs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllILSs(StBool value) {
        this.deleteAllILSs = value;
    }

    /**
     * Gets the value of the deleteAllApproaches property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllApproaches() {
        return deleteAllApproaches;
    }

    /**
     * Sets the value of the deleteAllApproaches property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllApproaches(StBool value) {
        this.deleteAllApproaches = value;
    }

    /**
     * Gets the value of the deleteAllDepartures property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllDepartures() {
        return deleteAllDepartures;
    }

    /**
     * Sets the value of the deleteAllDepartures property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllDepartures(StBool value) {
        this.deleteAllDepartures = value;
    }

    /**
     * Gets the value of the deleteAllArrivals property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllArrivals() {
        return deleteAllArrivals;
    }

    /**
     * Sets the value of the deleteAllArrivals property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllArrivals(StBool value) {
        this.deleteAllArrivals = value;
    }

    /**
     * Gets the value of the deleteAllFrequencies property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllFrequencies() {
        return deleteAllFrequencies;
    }

    /**
     * Sets the value of the deleteAllFrequencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllFrequencies(StBool value) {
        this.deleteAllFrequencies = value;
    }

}
