//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctDeleteAirport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctDeleteAirport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}grpDeleteAirportChildren" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="deleteAllApproaches" type="{}stBool" />
 *       &lt;attribute name="deleteAllApronLights" type="{}stBool" />
 *       &lt;attribute name="deleteAllAprons" type="{}stBool" />
 *       &lt;attribute name="deleteAllFrequencies" type="{}stBool" />
 *       &lt;attribute name="deleteAllHelipads" type="{}stBool" />
 *       &lt;attribute name="deleteAllRunways" type="{}stBool" />
 *       &lt;attribute name="deleteAllStarts" type="{}stBool" />
 *       &lt;attribute name="deleteAllTaxiways" type="{}stBool" />
 *       &lt;attribute name="deleteAllBlastFences" type="{}stBool" />
 *       &lt;attribute name="deleteAllBoundaryFences" type="{}stBool" />
 *       &lt;attribute name="deleteAllControlTowers" type="{}stBool" />
 *       &lt;attribute name="deleteAllJetways" type="{}stBool" />
 *       &lt;attribute name="deleteAllDepartures" type="{}stBool" />
 *       &lt;attribute name="deleteAllArrivals" type="{}stBool" />
 *       &lt;attribute name="deleteAllPaintedElements" type="{}stBool" />
 *       &lt;attribute name="deleteAllLightSupports" type="{}stBool" />
 *       &lt;attribute name="deleteAllTaxiwaySigns" type="{}stBool" />
 *       &lt;attribute name="deleteAllILSs" type="{}stBool" />
 *       &lt;attribute name="deleteAllTerminalWaypoints" type="{}stBool" />
 *       &lt;attribute name="deleteAllTerminalNDBs" type="{}stBool" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctDeleteAirport", propOrder = {
    "grpDeleteAirportChildren"
})
public class CtDeleteAirport {

    @XmlElements({
        @XmlElement(name = "DeleteRunway", type = CtDeleteRunway.class),
        @XmlElement(name = "DeleteStart", type = CtDeleteStart.class),
        @XmlElement(name = "DeleteFrequency", type = CtDeleteFrequency.class)
    })
    protected List<Object> grpDeleteAirportChildren;
    @XmlAttribute(name = "deleteAllApproaches")
    protected StBool deleteAllApproaches;
    @XmlAttribute(name = "deleteAllApronLights")
    protected StBool deleteAllApronLights;
    @XmlAttribute(name = "deleteAllAprons")
    protected StBool deleteAllAprons;
    @XmlAttribute(name = "deleteAllFrequencies")
    protected StBool deleteAllFrequencies;
    @XmlAttribute(name = "deleteAllHelipads")
    protected StBool deleteAllHelipads;
    @XmlAttribute(name = "deleteAllRunways")
    protected StBool deleteAllRunways;
    @XmlAttribute(name = "deleteAllStarts")
    protected StBool deleteAllStarts;
    @XmlAttribute(name = "deleteAllTaxiways")
    protected StBool deleteAllTaxiways;
    @XmlAttribute(name = "deleteAllBlastFences")
    protected StBool deleteAllBlastFences;
    @XmlAttribute(name = "deleteAllBoundaryFences")
    protected StBool deleteAllBoundaryFences;
    @XmlAttribute(name = "deleteAllControlTowers")
    protected StBool deleteAllControlTowers;
    @XmlAttribute(name = "deleteAllJetways")
    protected StBool deleteAllJetways;
    @XmlAttribute(name = "deleteAllDepartures")
    protected StBool deleteAllDepartures;
    @XmlAttribute(name = "deleteAllArrivals")
    protected StBool deleteAllArrivals;
    @XmlAttribute(name = "deleteAllPaintedElements")
    protected StBool deleteAllPaintedElements;
    @XmlAttribute(name = "deleteAllLightSupports")
    protected StBool deleteAllLightSupports;
    @XmlAttribute(name = "deleteAllTaxiwaySigns")
    protected StBool deleteAllTaxiwaySigns;
    @XmlAttribute(name = "deleteAllILSs")
    protected StBool deleteAllILSs;
    @XmlAttribute(name = "deleteAllTerminalWaypoints")
    protected StBool deleteAllTerminalWaypoints;
    @XmlAttribute(name = "deleteAllTerminalNDBs")
    protected StBool deleteAllTerminalNDBs;

    /**
     * Gets the value of the grpDeleteAirportChildren property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grpDeleteAirportChildren property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrpDeleteAirportChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtDeleteRunway }
     * {@link CtDeleteStart }
     * {@link CtDeleteFrequency }
     * 
     * 
     */
    public List<Object> getGrpDeleteAirportChildren() {
        if (grpDeleteAirportChildren == null) {
            grpDeleteAirportChildren = new ArrayList<Object>();
        }
        return this.grpDeleteAirportChildren;
    }

    /**
     * Gets the value of the deleteAllApproaches property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllApproaches() {
        return deleteAllApproaches;
    }

    /**
     * Sets the value of the deleteAllApproaches property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllApproaches(StBool value) {
        this.deleteAllApproaches = value;
    }

    /**
     * Gets the value of the deleteAllApronLights property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllApronLights() {
        return deleteAllApronLights;
    }

    /**
     * Sets the value of the deleteAllApronLights property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllApronLights(StBool value) {
        this.deleteAllApronLights = value;
    }

    /**
     * Gets the value of the deleteAllAprons property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllAprons() {
        return deleteAllAprons;
    }

    /**
     * Sets the value of the deleteAllAprons property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllAprons(StBool value) {
        this.deleteAllAprons = value;
    }

    /**
     * Gets the value of the deleteAllFrequencies property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllFrequencies() {
        return deleteAllFrequencies;
    }

    /**
     * Sets the value of the deleteAllFrequencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllFrequencies(StBool value) {
        this.deleteAllFrequencies = value;
    }

    /**
     * Gets the value of the deleteAllHelipads property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllHelipads() {
        return deleteAllHelipads;
    }

    /**
     * Sets the value of the deleteAllHelipads property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllHelipads(StBool value) {
        this.deleteAllHelipads = value;
    }

    /**
     * Gets the value of the deleteAllRunways property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllRunways() {
        return deleteAllRunways;
    }

    /**
     * Sets the value of the deleteAllRunways property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllRunways(StBool value) {
        this.deleteAllRunways = value;
    }

    /**
     * Gets the value of the deleteAllStarts property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllStarts() {
        return deleteAllStarts;
    }

    /**
     * Sets the value of the deleteAllStarts property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllStarts(StBool value) {
        this.deleteAllStarts = value;
    }

    /**
     * Gets the value of the deleteAllTaxiways property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllTaxiways() {
        return deleteAllTaxiways;
    }

    /**
     * Sets the value of the deleteAllTaxiways property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllTaxiways(StBool value) {
        this.deleteAllTaxiways = value;
    }

    /**
     * Gets the value of the deleteAllBlastFences property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllBlastFences() {
        return deleteAllBlastFences;
    }

    /**
     * Sets the value of the deleteAllBlastFences property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllBlastFences(StBool value) {
        this.deleteAllBlastFences = value;
    }

    /**
     * Gets the value of the deleteAllBoundaryFences property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllBoundaryFences() {
        return deleteAllBoundaryFences;
    }

    /**
     * Sets the value of the deleteAllBoundaryFences property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllBoundaryFences(StBool value) {
        this.deleteAllBoundaryFences = value;
    }

    /**
     * Gets the value of the deleteAllControlTowers property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllControlTowers() {
        return deleteAllControlTowers;
    }

    /**
     * Sets the value of the deleteAllControlTowers property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllControlTowers(StBool value) {
        this.deleteAllControlTowers = value;
    }

    /**
     * Gets the value of the deleteAllJetways property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllJetways() {
        return deleteAllJetways;
    }

    /**
     * Sets the value of the deleteAllJetways property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllJetways(StBool value) {
        this.deleteAllJetways = value;
    }

    /**
     * Gets the value of the deleteAllDepartures property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllDepartures() {
        return deleteAllDepartures;
    }

    /**
     * Sets the value of the deleteAllDepartures property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllDepartures(StBool value) {
        this.deleteAllDepartures = value;
    }

    /**
     * Gets the value of the deleteAllArrivals property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllArrivals() {
        return deleteAllArrivals;
    }

    /**
     * Sets the value of the deleteAllArrivals property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllArrivals(StBool value) {
        this.deleteAllArrivals = value;
    }

    /**
     * Gets the value of the deleteAllPaintedElements property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllPaintedElements() {
        return deleteAllPaintedElements;
    }

    /**
     * Sets the value of the deleteAllPaintedElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllPaintedElements(StBool value) {
        this.deleteAllPaintedElements = value;
    }

    /**
     * Gets the value of the deleteAllLightSupports property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllLightSupports() {
        return deleteAllLightSupports;
    }

    /**
     * Sets the value of the deleteAllLightSupports property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllLightSupports(StBool value) {
        this.deleteAllLightSupports = value;
    }

    /**
     * Gets the value of the deleteAllTaxiwaySigns property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllTaxiwaySigns() {
        return deleteAllTaxiwaySigns;
    }

    /**
     * Sets the value of the deleteAllTaxiwaySigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllTaxiwaySigns(StBool value) {
        this.deleteAllTaxiwaySigns = value;
    }

    /**
     * Gets the value of the deleteAllILSs property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllILSs() {
        return deleteAllILSs;
    }

    /**
     * Sets the value of the deleteAllILSs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllILSs(StBool value) {
        this.deleteAllILSs = value;
    }

    /**
     * Gets the value of the deleteAllTerminalWaypoints property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllTerminalWaypoints() {
        return deleteAllTerminalWaypoints;
    }

    /**
     * Sets the value of the deleteAllTerminalWaypoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllTerminalWaypoints(StBool value) {
        this.deleteAllTerminalWaypoints = value;
    }

    /**
     * Gets the value of the deleteAllTerminalNDBs property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDeleteAllTerminalNDBs() {
        return deleteAllTerminalNDBs;
    }

    /**
     * Sets the value of the deleteAllTerminalNDBs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDeleteAllTerminalNDBs(StBool value) {
        this.deleteAllTerminalNDBs = value;
    }

}
