//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ctExclusionRectangle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctExclusionRectangle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="latitudeMinimum" use="required" type="{}stLatitude" />
 *       &lt;attribute name="latitudeMaximum" use="required" type="{}stLatitude" />
 *       &lt;attribute name="longitudeMinimum" use="required" type="{}stLongitude" />
 *       &lt;attribute name="longitudeMaximum" use="required" type="{}stLongitude" />
 *       &lt;attribute name="excludeAllObjects" type="{}stBool" />
 *       &lt;attribute name="excludeBeaconObjects" type="{}stBool" />
 *       &lt;attribute name="excludeEffectObjects" type="{}stBool" />
 *       &lt;attribute name="excludeExtrusionBridgeObjects" type="{}stBool" />
 *       &lt;attribute name="excludeGenericBuildingObjects" type="{}stBool" />
 *       &lt;attribute name="excludeLibraryObjects" type="{}stBool" />
 *       &lt;attribute name="excludeTaxiwaySignObjects" type="{}stBool" />
 *       &lt;attribute name="excludeTriggerObjects" type="{}stBool" />
 *       &lt;attribute name="excludeWindsockObjects" type="{}stBool" />
 *       &lt;attribute name="excludeSimObjects" type="{}stBool" />
 *       &lt;attribute name="excludeWorldScripts" type="{}stBool" />
 *       &lt;attribute name="excludeCarParking" type="{}stBool" />
 *       &lt;attribute name="excludeRectangles" type="{}stBool" />
 *       &lt;attribute name="excludePolygons" type="{}stBool" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctExclusionRectangle")
public class CtExclusionRectangle {

    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "latitudeMinimum", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Double latitudeMinimum;
    @XmlAttribute(name = "latitudeMaximum", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Double latitudeMaximum;
    @XmlAttribute(name = "longitudeMinimum", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    protected Double longitudeMinimum;
    @XmlAttribute(name = "longitudeMaximum", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    protected Double longitudeMaximum;
    @XmlAttribute(name = "excludeAllObjects")
    protected StBool excludeAllObjects;
    @XmlAttribute(name = "excludeBeaconObjects")
    protected StBool excludeBeaconObjects;
    @XmlAttribute(name = "excludeEffectObjects")
    protected StBool excludeEffectObjects;
    @XmlAttribute(name = "excludeExtrusionBridgeObjects")
    protected StBool excludeExtrusionBridgeObjects;
    @XmlAttribute(name = "excludeGenericBuildingObjects")
    protected StBool excludeGenericBuildingObjects;
    @XmlAttribute(name = "excludeLibraryObjects")
    protected StBool excludeLibraryObjects;
    @XmlAttribute(name = "excludeTaxiwaySignObjects")
    protected StBool excludeTaxiwaySignObjects;
    @XmlAttribute(name = "excludeTriggerObjects")
    protected StBool excludeTriggerObjects;
    @XmlAttribute(name = "excludeWindsockObjects")
    protected StBool excludeWindsockObjects;
    @XmlAttribute(name = "excludeSimObjects")
    protected StBool excludeSimObjects;
    @XmlAttribute(name = "excludeWorldScripts")
    protected StBool excludeWorldScripts;
    @XmlAttribute(name = "excludeCarParking")
    protected StBool excludeCarParking;
    @XmlAttribute(name = "excludeRectangles")
    protected StBool excludeRectangles;
    @XmlAttribute(name = "excludePolygons")
    protected StBool excludePolygons;

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the latitudeMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getLatitudeMinimum() {
        return latitudeMinimum;
    }

    /**
     * Sets the value of the latitudeMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitudeMinimum(Double value) {
        this.latitudeMinimum = value;
    }

    /**
     * Gets the value of the latitudeMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getLatitudeMaximum() {
        return latitudeMaximum;
    }

    /**
     * Sets the value of the latitudeMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitudeMaximum(Double value) {
        this.latitudeMaximum = value;
    }

    /**
     * Gets the value of the longitudeMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getLongitudeMinimum() {
        return longitudeMinimum;
    }

    /**
     * Sets the value of the longitudeMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitudeMinimum(Double value) {
        this.longitudeMinimum = value;
    }

    /**
     * Gets the value of the longitudeMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getLongitudeMaximum() {
        return longitudeMaximum;
    }

    /**
     * Sets the value of the longitudeMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitudeMaximum(Double value) {
        this.longitudeMaximum = value;
    }

    /**
     * Gets the value of the excludeAllObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeAllObjects() {
        return excludeAllObjects;
    }

    /**
     * Sets the value of the excludeAllObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeAllObjects(StBool value) {
        this.excludeAllObjects = value;
    }

    /**
     * Gets the value of the excludeBeaconObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeBeaconObjects() {
        return excludeBeaconObjects;
    }

    /**
     * Sets the value of the excludeBeaconObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeBeaconObjects(StBool value) {
        this.excludeBeaconObjects = value;
    }

    /**
     * Gets the value of the excludeEffectObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeEffectObjects() {
        return excludeEffectObjects;
    }

    /**
     * Sets the value of the excludeEffectObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeEffectObjects(StBool value) {
        this.excludeEffectObjects = value;
    }

    /**
     * Gets the value of the excludeExtrusionBridgeObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeExtrusionBridgeObjects() {
        return excludeExtrusionBridgeObjects;
    }

    /**
     * Sets the value of the excludeExtrusionBridgeObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeExtrusionBridgeObjects(StBool value) {
        this.excludeExtrusionBridgeObjects = value;
    }

    /**
     * Gets the value of the excludeGenericBuildingObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeGenericBuildingObjects() {
        return excludeGenericBuildingObjects;
    }

    /**
     * Sets the value of the excludeGenericBuildingObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeGenericBuildingObjects(StBool value) {
        this.excludeGenericBuildingObjects = value;
    }

    /**
     * Gets the value of the excludeLibraryObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeLibraryObjects() {
        return excludeLibraryObjects;
    }

    /**
     * Sets the value of the excludeLibraryObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeLibraryObjects(StBool value) {
        this.excludeLibraryObjects = value;
    }

    /**
     * Gets the value of the excludeTaxiwaySignObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeTaxiwaySignObjects() {
        return excludeTaxiwaySignObjects;
    }

    /**
     * Sets the value of the excludeTaxiwaySignObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeTaxiwaySignObjects(StBool value) {
        this.excludeTaxiwaySignObjects = value;
    }

    /**
     * Gets the value of the excludeTriggerObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeTriggerObjects() {
        return excludeTriggerObjects;
    }

    /**
     * Sets the value of the excludeTriggerObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeTriggerObjects(StBool value) {
        this.excludeTriggerObjects = value;
    }

    /**
     * Gets the value of the excludeWindsockObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeWindsockObjects() {
        return excludeWindsockObjects;
    }

    /**
     * Sets the value of the excludeWindsockObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeWindsockObjects(StBool value) {
        this.excludeWindsockObjects = value;
    }

    /**
     * Gets the value of the excludeSimObjects property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeSimObjects() {
        return excludeSimObjects;
    }

    /**
     * Sets the value of the excludeSimObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeSimObjects(StBool value) {
        this.excludeSimObjects = value;
    }

    /**
     * Gets the value of the excludeWorldScripts property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeWorldScripts() {
        return excludeWorldScripts;
    }

    /**
     * Sets the value of the excludeWorldScripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeWorldScripts(StBool value) {
        this.excludeWorldScripts = value;
    }

    /**
     * Gets the value of the excludeCarParking property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeCarParking() {
        return excludeCarParking;
    }

    /**
     * Sets the value of the excludeCarParking property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeCarParking(StBool value) {
        this.excludeCarParking = value;
    }

    /**
     * Gets the value of the excludeRectangles property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludeRectangles() {
        return excludeRectangles;
    }

    /**
     * Sets the value of the excludeRectangles property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludeRectangles(StBool value) {
        this.excludeRectangles = value;
    }

    /**
     * Gets the value of the excludePolygons property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getExcludePolygons() {
        return excludePolygons;
    }

    /**
     * Sets the value of the excludePolygons property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setExcludePolygons(StBool value) {
        this.excludePolygons = value;
    }

}
