//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctFacilityMaterial complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctFacilityMaterial">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="guid" use="required" type="{}stGuid" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tilingU" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="tilingV" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="width" type="{}stDistance" />
 *       &lt;attribute name="falloff" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="opacity" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctFacilityMaterial")
public class CtFacilityMaterial {

    @XmlAttribute(name = "guid", required = true)
    protected String guid;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "tilingU", required = true)
    protected double tilingU;
    @XmlAttribute(name = "tilingV", required = true)
    protected double tilingV;
    @XmlAttribute(name = "width")
    protected String width;
    @XmlAttribute(name = "falloff")
    protected Double falloff;
    @XmlAttribute(name = "opacity")
    protected BigInteger opacity;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the tilingU property.
     * 
     */
    public double getTilingU() {
        return tilingU;
    }

    /**
     * Sets the value of the tilingU property.
     * 
     */
    public void setTilingU(double value) {
        this.tilingU = value;
    }

    /**
     * Gets the value of the tilingV property.
     * 
     */
    public double getTilingV() {
        return tilingV;
    }

    /**
     * Sets the value of the tilingV property.
     * 
     */
    public void setTilingV(double value) {
        this.tilingV = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the falloff property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFalloff() {
        return falloff;
    }

    /**
     * Sets the value of the falloff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFalloff(Double value) {
        this.falloff = value;
    }

    /**
     * Gets the value of the opacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOpacity() {
        return opacity;
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOpacity(BigInteger value) {
        this.opacity = value;
    }

}
