//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctFSData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctFSData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}grpFSDataChildren" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="patch" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctFSData", propOrder = {
    "grpFSDataChildren"
})
public class CtFSData {

    @XmlElementRefs({
        @XmlElementRef(name = "Vor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Rectangle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Waypoint", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ModelData", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Group", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ExclusionRectangle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Ndb", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Boundary", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GLTFData", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Location", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Reward", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Airport", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SceneryObject", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ExtrusionBridge", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LandmarkLocation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TimeZone", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DeleteNavigation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AiracCycle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Marker", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Geopol", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> grpFSDataChildren;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "timestamp")
    protected String timestamp;
    @XmlAttribute(name = "patch")
    protected String patch;

    /**
     * Gets the value of the grpFSDataChildren property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grpFSDataChildren property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrpFSDataChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CtVor }{@code >}
     * {@link JAXBElement }{@code <}{@link CtRectangle }{@code >}
     * {@link JAXBElement }{@code <}{@link CtWaypoint }{@code >}
     * {@link JAXBElement }{@code <}{@link CtModelData }{@code >}
     * {@link JAXBElement }{@code <}{@link CtGroup }{@code >}
     * {@link JAXBElement }{@code <}{@link CtExclusionRectangle }{@code >}
     * {@link JAXBElement }{@code <}{@link CtNdb }{@code >}
     * {@link JAXBElement }{@code <}{@link CtBoundary }{@code >}
     * {@link JAXBElement }{@code <}{@link CtGLTFData }{@code >}
     * {@link JAXBElement }{@code <}{@link CtAirport }{@code >}
     * {@link JAXBElement }{@code <}{@link CtReward }{@code >}
     * {@link JAXBElement }{@code <}{@link CtAirport }{@code >}
     * {@link JAXBElement }{@code <}{@link CtSceneryObject }{@code >}
     * {@link JAXBElement }{@code <}{@link CtExtrusionBridge }{@code >}
     * {@link JAXBElement }{@code <}{@link CtLandmarkLocation }{@code >}
     * {@link JAXBElement }{@code <}{@link CtTimeZone }{@code >}
     * {@link JAXBElement }{@code <}{@link CtDeleteNavigation }{@code >}
     * {@link JAXBElement }{@code <}{@link CtAiracCycle }{@code >}
     * {@link JAXBElement }{@code <}{@link CtMarker }{@code >}
     * {@link JAXBElement }{@code <}{@link CtGeopol }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getGrpFSDataChildren() {
        if (grpFSDataChildren == null) {
            grpFSDataChildren = new ArrayList<JAXBElement<?>>();
        }
        return this.grpFSDataChildren;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the patch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatch() {
        return patch;
    }

    /**
     * Sets the value of the patch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatch(String value) {
        this.patch = value;
    }

}
