//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctLights complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctLights">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="edge" type="{}stLights" />
 *       &lt;attribute name="center" type="{}stLights" />
 *       &lt;attribute name="centerRed" type="{}stBool" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctLights")
public class CtLights {

    @XmlAttribute(name = "edge")
    protected StLights edge;
    @XmlAttribute(name = "center")
    protected StLights center;
    @XmlAttribute(name = "centerRed")
    protected StBool centerRed;

    /**
     * Gets the value of the edge property.
     * 
     * @return
     *     possible object is
     *     {@link StLights }
     *     
     */
    public StLights getEdge() {
        return edge;
    }

    /**
     * Sets the value of the edge property.
     * 
     * @param value
     *     allowed object is
     *     {@link StLights }
     *     
     */
    public void setEdge(StLights value) {
        this.edge = value;
    }

    /**
     * Gets the value of the center property.
     * 
     * @return
     *     possible object is
     *     {@link StLights }
     *     
     */
    public StLights getCenter() {
        return center;
    }

    /**
     * Sets the value of the center property.
     * 
     * @param value
     *     allowed object is
     *     {@link StLights }
     *     
     */
    public void setCenter(StLights value) {
        this.center = value;
    }

    /**
     * Gets the value of the centerRed property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getCenterRed() {
        return centerRed;
    }

    /**
     * Sets the value of the centerRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setCenterRed(StBool value) {
        this.centerRed = value;
    }

}
