//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctMarkings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctMarkings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="alternateThreshold" type="{}stBool" />
 *       &lt;attribute name="alternateTouchdown" type="{}stBool" />
 *       &lt;attribute name="alternateFixedDistance" type="{}stBool" />
 *       &lt;attribute name="alternatePrecision" type="{}stBool" />
 *       &lt;attribute name="leadingZeroIdent" type="{}stBool" />
 *       &lt;attribute name="noThresholdEndArrows" type="{}stBool" />
 *       &lt;attribute name="edges" type="{}stBool" />
 *       &lt;attribute name="threshold" type="{}stBool" />
 *       &lt;attribute name="fixedDistance" type="{}stBool" />
 *       &lt;attribute name="dashes" type="{}stBool" />
 *       &lt;attribute name="ident" type="{}stBool" />
 *       &lt;attribute name="primaryClosed" type="{}stBool" />
 *       &lt;attribute name="secondaryClosed" type="{}stBool" />
 *       &lt;attribute name="touchdown" type="{}stBool" />
 *       &lt;attribute name="precision" type="{}stBool" />
 *       &lt;attribute name="edgePavement" type="{}stBool" />
 *       &lt;attribute name="singleEnd" type="{}stBool" />
 *       &lt;attribute name="primaryStol" type="{}stBool" />
 *       &lt;attribute name="secondaryStol" type="{}stBool" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctMarkings")
public class CtMarkings {

    @XmlAttribute(name = "alternateThreshold")
    protected StBool alternateThreshold;
    @XmlAttribute(name = "alternateTouchdown")
    protected StBool alternateTouchdown;
    @XmlAttribute(name = "alternateFixedDistance")
    protected StBool alternateFixedDistance;
    @XmlAttribute(name = "alternatePrecision")
    protected StBool alternatePrecision;
    @XmlAttribute(name = "leadingZeroIdent")
    protected StBool leadingZeroIdent;
    @XmlAttribute(name = "noThresholdEndArrows")
    protected StBool noThresholdEndArrows;
    @XmlAttribute(name = "edges")
    protected StBool edges;
    @XmlAttribute(name = "threshold")
    protected StBool threshold;
    @XmlAttribute(name = "fixedDistance")
    protected StBool fixedDistance;
    @XmlAttribute(name = "dashes")
    protected StBool dashes;
    @XmlAttribute(name = "ident")
    protected StBool ident;
    @XmlAttribute(name = "primaryClosed")
    protected StBool primaryClosed;
    @XmlAttribute(name = "secondaryClosed")
    protected StBool secondaryClosed;
    @XmlAttribute(name = "touchdown")
    protected StBool touchdown;
    @XmlAttribute(name = "precision")
    protected StBool precision;
    @XmlAttribute(name = "edgePavement")
    protected StBool edgePavement;
    @XmlAttribute(name = "singleEnd")
    protected StBool singleEnd;
    @XmlAttribute(name = "primaryStol")
    protected StBool primaryStol;
    @XmlAttribute(name = "secondaryStol")
    protected StBool secondaryStol;

    /**
     * Gets the value of the alternateThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getAlternateThreshold() {
        return alternateThreshold;
    }

    /**
     * Sets the value of the alternateThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setAlternateThreshold(StBool value) {
        this.alternateThreshold = value;
    }

    /**
     * Gets the value of the alternateTouchdown property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getAlternateTouchdown() {
        return alternateTouchdown;
    }

    /**
     * Sets the value of the alternateTouchdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setAlternateTouchdown(StBool value) {
        this.alternateTouchdown = value;
    }

    /**
     * Gets the value of the alternateFixedDistance property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getAlternateFixedDistance() {
        return alternateFixedDistance;
    }

    /**
     * Sets the value of the alternateFixedDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setAlternateFixedDistance(StBool value) {
        this.alternateFixedDistance = value;
    }

    /**
     * Gets the value of the alternatePrecision property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getAlternatePrecision() {
        return alternatePrecision;
    }

    /**
     * Sets the value of the alternatePrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setAlternatePrecision(StBool value) {
        this.alternatePrecision = value;
    }

    /**
     * Gets the value of the leadingZeroIdent property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getLeadingZeroIdent() {
        return leadingZeroIdent;
    }

    /**
     * Sets the value of the leadingZeroIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setLeadingZeroIdent(StBool value) {
        this.leadingZeroIdent = value;
    }

    /**
     * Gets the value of the noThresholdEndArrows property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getNoThresholdEndArrows() {
        return noThresholdEndArrows;
    }

    /**
     * Sets the value of the noThresholdEndArrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setNoThresholdEndArrows(StBool value) {
        this.noThresholdEndArrows = value;
    }

    /**
     * Gets the value of the edges property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getEdges() {
        return edges;
    }

    /**
     * Sets the value of the edges property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setEdges(StBool value) {
        this.edges = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setThreshold(StBool value) {
        this.threshold = value;
    }

    /**
     * Gets the value of the fixedDistance property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getFixedDistance() {
        return fixedDistance;
    }

    /**
     * Sets the value of the fixedDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setFixedDistance(StBool value) {
        this.fixedDistance = value;
    }

    /**
     * Gets the value of the dashes property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getDashes() {
        return dashes;
    }

    /**
     * Sets the value of the dashes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setDashes(StBool value) {
        this.dashes = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setIdent(StBool value) {
        this.ident = value;
    }

    /**
     * Gets the value of the primaryClosed property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getPrimaryClosed() {
        return primaryClosed;
    }

    /**
     * Sets the value of the primaryClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setPrimaryClosed(StBool value) {
        this.primaryClosed = value;
    }

    /**
     * Gets the value of the secondaryClosed property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getSecondaryClosed() {
        return secondaryClosed;
    }

    /**
     * Sets the value of the secondaryClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setSecondaryClosed(StBool value) {
        this.secondaryClosed = value;
    }

    /**
     * Gets the value of the touchdown property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getTouchdown() {
        return touchdown;
    }

    /**
     * Sets the value of the touchdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setTouchdown(StBool value) {
        this.touchdown = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setPrecision(StBool value) {
        this.precision = value;
    }

    /**
     * Gets the value of the edgePavement property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getEdgePavement() {
        return edgePavement;
    }

    /**
     * Sets the value of the edgePavement property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setEdgePavement(StBool value) {
        this.edgePavement = value;
    }

    /**
     * Gets the value of the singleEnd property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getSingleEnd() {
        return singleEnd;
    }

    /**
     * Sets the value of the singleEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setSingleEnd(StBool value) {
        this.singleEnd = value;
    }

    /**
     * Gets the value of the primaryStol property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getPrimaryStol() {
        return primaryStol;
    }

    /**
     * Sets the value of the primaryStol property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setPrimaryStol(StBool value) {
        this.primaryStol = value;
    }

    /**
     * Gets the value of the secondaryStol property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getSecondaryStol() {
        return secondaryStol;
    }

    /**
     * Sets the value of the secondaryStol property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setSecondaryStol(StBool value) {
        this.secondaryStol = value;
    }

}
