//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctPaintedPolygon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctPaintedPolygon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Vertex" type="{}ctVertexLL" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="red" use="required" type="{}stRatio" />
 *       &lt;attribute name="green" use="required" type="{}stRatio" />
 *       &lt;attribute name="blue" use="required" type="{}stRatio" />
 *       &lt;attribute name="alpha" use="required" type="{}stRatio" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctPaintedPolygon", propOrder = {
    "vertex"
})
public class CtPaintedPolygon {

    @XmlElement(name = "Vertex")
    protected List<CtVertexLL> vertex;
    @XmlAttribute(name = "red", required = true)
    protected double red;
    @XmlAttribute(name = "green", required = true)
    protected double green;
    @XmlAttribute(name = "blue", required = true)
    protected double blue;
    @XmlAttribute(name = "alpha", required = true)
    protected double alpha;

    /**
     * Gets the value of the vertex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vertex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVertex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtVertexLL }
     * 
     * 
     */
    public List<CtVertexLL> getVertex() {
        if (vertex == null) {
            vertex = new ArrayList<CtVertexLL>();
        }
        return this.vertex;
    }

    /**
     * Gets the value of the red property.
     * 
     */
    public double getRed() {
        return red;
    }

    /**
     * Sets the value of the red property.
     * 
     */
    public void setRed(double value) {
        this.red = value;
    }

    /**
     * Gets the value of the green property.
     * 
     */
    public double getGreen() {
        return green;
    }

    /**
     * Sets the value of the green property.
     * 
     */
    public void setGreen(double value) {
        this.green = value;
    }

    /**
     * Gets the value of the blue property.
     * 
     */
    public double getBlue() {
        return blue;
    }

    /**
     * Sets the value of the blue property.
     * 
     */
    public void setBlue(double value) {
        this.blue = value;
    }

    /**
     * Gets the value of the alpha property.
     * 
     */
    public double getAlpha() {
        return alpha;
    }

    /**
     * Sets the value of the alpha property.
     * 
     */
    public void setAlpha(double value) {
        this.alpha = value;
    }

}
