//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctPreviousNext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctPreviousNext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="waypointRegion" type="{}stString2" />
 *       &lt;attribute name="waypointIdent" type="{}stString5" />
 *       &lt;attribute name="waypointType" type="{}stWaypointType" />
 *       &lt;attribute name="altitudeMinimum" type="{}stAltitude" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctPreviousNext")
public class CtPreviousNext {

    @XmlAttribute(name = "waypointRegion")
    protected String waypointRegion;
    @XmlAttribute(name = "waypointIdent")
    protected String waypointIdent;
    @XmlAttribute(name = "waypointType")
    protected StWaypointType waypointType;
    @XmlAttribute(name = "altitudeMinimum")
    protected String altitudeMinimum;

    /**
     * Gets the value of the waypointRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaypointRegion() {
        return waypointRegion;
    }

    /**
     * Sets the value of the waypointRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaypointRegion(String value) {
        this.waypointRegion = value;
    }

    /**
     * Gets the value of the waypointIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaypointIdent() {
        return waypointIdent;
    }

    /**
     * Sets the value of the waypointIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaypointIdent(String value) {
        this.waypointIdent = value;
    }

    /**
     * Gets the value of the waypointType property.
     * 
     * @return
     *     possible object is
     *     {@link StWaypointType }
     *     
     */
    public StWaypointType getWaypointType() {
        return waypointType;
    }

    /**
     * Sets the value of the waypointType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StWaypointType }
     *     
     */
    public void setWaypointType(StWaypointType value) {
        this.waypointType = value;
    }

    /**
     * Gets the value of the altitudeMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltitudeMinimum() {
        return altitudeMinimum;
    }

    /**
     * Sets the value of the altitudeMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltitudeMinimum(String value) {
        this.altitudeMinimum = value;
    }

}
