//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctPyramidalBuilding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctPyramidalBuilding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sizeX" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="sizeZ" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="sizeTopX" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="sizeTopZ" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="sizeBottomY" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexBottomX" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexBottomZ" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="sizeWindowY" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexWindowX" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexWindowY" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexWindowZ" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="sizeTopY" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexTopX" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexTopZ" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexRoofX" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="textureIndexRoofZ" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctPyramidalBuilding")
public class CtPyramidalBuilding {

    @XmlAttribute(name = "sizeX")
    protected Double sizeX;
    @XmlAttribute(name = "sizeZ")
    protected Double sizeZ;
    @XmlAttribute(name = "sizeTopX")
    protected Double sizeTopX;
    @XmlAttribute(name = "sizeTopZ")
    protected Double sizeTopZ;
    @XmlAttribute(name = "sizeBottomY")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sizeBottomY;
    @XmlAttribute(name = "textureIndexBottomX")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexBottomX;
    @XmlAttribute(name = "textureIndexBottomZ")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexBottomZ;
    @XmlAttribute(name = "sizeWindowY")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sizeWindowY;
    @XmlAttribute(name = "textureIndexWindowX")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexWindowX;
    @XmlAttribute(name = "textureIndexWindowY")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexWindowY;
    @XmlAttribute(name = "textureIndexWindowZ")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexWindowZ;
    @XmlAttribute(name = "sizeTopY")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sizeTopY;
    @XmlAttribute(name = "textureIndexTopX")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexTopX;
    @XmlAttribute(name = "textureIndexTopZ")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexTopZ;
    @XmlAttribute(name = "textureIndexRoofX")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexRoofX;
    @XmlAttribute(name = "textureIndexRoofZ")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger textureIndexRoofZ;

    /**
     * Gets the value of the sizeX property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSizeX() {
        return sizeX;
    }

    /**
     * Sets the value of the sizeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSizeX(Double value) {
        this.sizeX = value;
    }

    /**
     * Gets the value of the sizeZ property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSizeZ() {
        return sizeZ;
    }

    /**
     * Sets the value of the sizeZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSizeZ(Double value) {
        this.sizeZ = value;
    }

    /**
     * Gets the value of the sizeTopX property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSizeTopX() {
        return sizeTopX;
    }

    /**
     * Sets the value of the sizeTopX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSizeTopX(Double value) {
        this.sizeTopX = value;
    }

    /**
     * Gets the value of the sizeTopZ property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSizeTopZ() {
        return sizeTopZ;
    }

    /**
     * Sets the value of the sizeTopZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSizeTopZ(Double value) {
        this.sizeTopZ = value;
    }

    /**
     * Gets the value of the sizeBottomY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSizeBottomY() {
        return sizeBottomY;
    }

    /**
     * Sets the value of the sizeBottomY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSizeBottomY(BigInteger value) {
        this.sizeBottomY = value;
    }

    /**
     * Gets the value of the textureIndexBottomX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexBottomX() {
        return textureIndexBottomX;
    }

    /**
     * Sets the value of the textureIndexBottomX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexBottomX(BigInteger value) {
        this.textureIndexBottomX = value;
    }

    /**
     * Gets the value of the textureIndexBottomZ property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexBottomZ() {
        return textureIndexBottomZ;
    }

    /**
     * Sets the value of the textureIndexBottomZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexBottomZ(BigInteger value) {
        this.textureIndexBottomZ = value;
    }

    /**
     * Gets the value of the sizeWindowY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSizeWindowY() {
        return sizeWindowY;
    }

    /**
     * Sets the value of the sizeWindowY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSizeWindowY(BigInteger value) {
        this.sizeWindowY = value;
    }

    /**
     * Gets the value of the textureIndexWindowX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexWindowX() {
        return textureIndexWindowX;
    }

    /**
     * Sets the value of the textureIndexWindowX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexWindowX(BigInteger value) {
        this.textureIndexWindowX = value;
    }

    /**
     * Gets the value of the textureIndexWindowY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexWindowY() {
        return textureIndexWindowY;
    }

    /**
     * Sets the value of the textureIndexWindowY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexWindowY(BigInteger value) {
        this.textureIndexWindowY = value;
    }

    /**
     * Gets the value of the textureIndexWindowZ property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexWindowZ() {
        return textureIndexWindowZ;
    }

    /**
     * Sets the value of the textureIndexWindowZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexWindowZ(BigInteger value) {
        this.textureIndexWindowZ = value;
    }

    /**
     * Gets the value of the sizeTopY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSizeTopY() {
        return sizeTopY;
    }

    /**
     * Sets the value of the sizeTopY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSizeTopY(BigInteger value) {
        this.sizeTopY = value;
    }

    /**
     * Gets the value of the textureIndexTopX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexTopX() {
        return textureIndexTopX;
    }

    /**
     * Sets the value of the textureIndexTopX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexTopX(BigInteger value) {
        this.textureIndexTopX = value;
    }

    /**
     * Gets the value of the textureIndexTopZ property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexTopZ() {
        return textureIndexTopZ;
    }

    /**
     * Sets the value of the textureIndexTopZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexTopZ(BigInteger value) {
        this.textureIndexTopZ = value;
    }

    /**
     * Gets the value of the textureIndexRoofX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexRoofX() {
        return textureIndexRoofX;
    }

    /**
     * Sets the value of the textureIndexRoofX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexRoofX(BigInteger value) {
        this.textureIndexRoofX = value;
    }

    /**
     * Gets the value of the textureIndexRoofZ property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextureIndexRoofZ() {
        return textureIndexRoofZ;
    }

    /**
     * Sets the value of the textureIndexRoofZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextureIndexRoofZ(BigInteger value) {
        this.textureIndexRoofZ = value;
    }

}
