//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctRandomAttach complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctRandomAttach">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="randomness" type="{}stRandomness" />
 *       &lt;attribute name="probability" type="{}stProbability" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctRandomAttach")
public class CtRandomAttach {

    @XmlAttribute(name = "randomness")
    protected StRandomness randomness;
    @XmlAttribute(name = "probability")
    protected Double probability;

    /**
     * Gets the value of the randomness property.
     * 
     * @return
     *     possible object is
     *     {@link StRandomness }
     *     
     */
    public StRandomness getRandomness() {
        return randomness;
    }

    /**
     * Sets the value of the randomness property.
     * 
     * @param value
     *     allowed object is
     *     {@link StRandomness }
     *     
     */
    public void setRandomness(StRandomness value) {
        this.randomness = value;
    }

    /**
     * Gets the value of the probability property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getProbability() {
        return probability;
    }

    /**
     * Sets the value of the probability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProbability(Double value) {
        this.probability = value;
    }

}
