//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ctSceneryObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctSceneryObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BiasXYZ" type="{}ctBias" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element name="NoAutogenSuppression" type="{}ctNoAutogenSuppression" minOccurs="0"/>
 *           &lt;element name="NoCrash" type="{}ctNoCrash" minOccurs="0"/>
 *           &lt;element name="NoFog" type="{}ctNoFog" minOccurs="0"/>
 *           &lt;element name="NoShadow" type="{}ctNoShadow" minOccurs="0"/>
 *           &lt;element name="NoZWrite" type="{}ctNoZWrite" minOccurs="0"/>
 *           &lt;element name="NoZTest" type="{}ctNoZTest" minOccurs="0"/>
 *           &lt;element name="HideOnTIN" type="{}ctHideOnTIN" minOccurs="0"/>
 *           &lt;element name="NoSnow" type="{}ctNoSnow" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;choice>
 *           &lt;element name="Beacon" type="{}ctBeacon" minOccurs="0"/>
 *           &lt;element name="Effect" type="{}ctEffect" minOccurs="0"/>
 *           &lt;element name="GenericBuilding" type="{}ctGenericBuilding" minOccurs="0"/>
 *           &lt;element name="LibraryObject" type="{}ctLibraryObject" minOccurs="0"/>
 *           &lt;element name="Trigger" type="{}ctTrigger" minOccurs="0"/>
 *           &lt;element name="Windsock" type="{}ctWindsock" minOccurs="0"/>
 *           &lt;element name="SimObject" type="{}ctSimObject" minOccurs="0"/>
 *           &lt;element name="WorldScript" type="{}ctWorldScript" minOccurs="0"/>
 *           &lt;element name="CarParking" type="{}ctCarParking" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="AttachedObject" type="{}ctAttachedObject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="instanceId" type="{}stGuid" />
 *       &lt;attribute name="lat" type="{}stLatitude" />
 *       &lt;attribute name="lon" type="{}stLongitude" />
 *       &lt;attribute name="alt" type="{}stAltitude" />
 *       &lt;attribute name="altitudeIsAgl" type="{}stBool" />
 *       &lt;attribute name="snapToGround" type="{}stBool" />
 *       &lt;attribute name="snapToNormal" type="{}stBool" />
 *       &lt;attribute name="pitch" type="{}stAngle" />
 *       &lt;attribute name="bank" type="{}stAngle" />
 *       &lt;attribute name="heading" type="{}stHeading" />
 *       &lt;attribute name="imageComplexity" type="{}stComplexity" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctSceneryObject", propOrder = {
    "biasXYZ",
    "noAutogenSuppression",
    "noCrash",
    "noFog",
    "noShadow",
    "noZWrite",
    "noZTest",
    "hideOnTIN",
    "noSnow",
    "beacon",
    "effect",
    "genericBuilding",
    "libraryObject",
    "trigger",
    "windsock",
    "simObject",
    "worldScript",
    "carParking",
    "attachedObject"
})
public class CtSceneryObject {

    @XmlElement(name = "BiasXYZ")
    protected CtBias biasXYZ;
    @XmlElement(name = "NoAutogenSuppression")
    protected CtNoAutogenSuppression noAutogenSuppression;
    @XmlElement(name = "NoCrash")
    protected CtNoCrash noCrash;
    @XmlElement(name = "NoFog")
    protected CtNoFog noFog;
    @XmlElement(name = "NoShadow")
    protected CtNoShadow noShadow;
    @XmlElement(name = "NoZWrite")
    protected CtNoZWrite noZWrite;
    @XmlElement(name = "NoZTest")
    protected CtNoZTest noZTest;
    @XmlElement(name = "HideOnTIN")
    protected CtHideOnTIN hideOnTIN;
    @XmlElement(name = "NoSnow")
    protected CtNoSnow noSnow;
    @XmlElement(name = "Beacon")
    protected CtBeacon beacon;
    @XmlElement(name = "Effect")
    protected CtEffect effect;
    @XmlElement(name = "GenericBuilding")
    protected CtGenericBuilding genericBuilding;
    @XmlElement(name = "LibraryObject")
    protected CtLibraryObject libraryObject;
    @XmlElement(name = "Trigger")
    protected CtTrigger trigger;
    @XmlElement(name = "Windsock")
    protected CtWindsock windsock;
    @XmlElement(name = "SimObject")
    protected CtSimObject simObject;
    @XmlElement(name = "WorldScript")
    protected CtWorldScript worldScript;
    @XmlElement(name = "CarParking")
    protected CtCarParking carParking;
    @XmlElement(name = "AttachedObject")
    protected List<CtAttachedObject> attachedObject;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "instanceId")
    protected String instanceId;
    @XmlAttribute(name = "lat")
    protected String lat;
    @XmlAttribute(name = "lon")
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Double lon;
    @XmlAttribute(name = "alt")
    protected String alt;
    @XmlAttribute(name = "altitudeIsAgl")
    protected StBool altitudeIsAgl;
    @XmlAttribute(name = "snapToGround")
    protected StBool snapToGround;
    @XmlAttribute(name = "snapToNormal")
    protected StBool snapToNormal;
    @XmlAttribute(name = "pitch")
    protected Double pitch;
    @XmlAttribute(name = "bank")
    protected Double bank;
    @XmlAttribute(name = "heading")
    protected Double heading;
    @XmlAttribute(name = "imageComplexity")
    protected StComplexity imageComplexity;

    /**
     * Gets the value of the biasXYZ property.
     * 
     * @return
     *     possible object is
     *     {@link CtBias }
     *     
     */
    public CtBias getBiasXYZ() {
        return biasXYZ;
    }

    /**
     * Sets the value of the biasXYZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBias }
     *     
     */
    public void setBiasXYZ(CtBias value) {
        this.biasXYZ = value;
    }

    /**
     * Gets the value of the noAutogenSuppression property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoAutogenSuppression }
     *     
     */
    public CtNoAutogenSuppression getNoAutogenSuppression() {
        return noAutogenSuppression;
    }

    /**
     * Sets the value of the noAutogenSuppression property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoAutogenSuppression }
     *     
     */
    public void setNoAutogenSuppression(CtNoAutogenSuppression value) {
        this.noAutogenSuppression = value;
    }

    /**
     * Gets the value of the noCrash property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoCrash }
     *     
     */
    public CtNoCrash getNoCrash() {
        return noCrash;
    }

    /**
     * Sets the value of the noCrash property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoCrash }
     *     
     */
    public void setNoCrash(CtNoCrash value) {
        this.noCrash = value;
    }

    /**
     * Gets the value of the noFog property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoFog }
     *     
     */
    public CtNoFog getNoFog() {
        return noFog;
    }

    /**
     * Sets the value of the noFog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoFog }
     *     
     */
    public void setNoFog(CtNoFog value) {
        this.noFog = value;
    }

    /**
     * Gets the value of the noShadow property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoShadow }
     *     
     */
    public CtNoShadow getNoShadow() {
        return noShadow;
    }

    /**
     * Sets the value of the noShadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoShadow }
     *     
     */
    public void setNoShadow(CtNoShadow value) {
        this.noShadow = value;
    }

    /**
     * Gets the value of the noZWrite property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoZWrite }
     *     
     */
    public CtNoZWrite getNoZWrite() {
        return noZWrite;
    }

    /**
     * Sets the value of the noZWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoZWrite }
     *     
     */
    public void setNoZWrite(CtNoZWrite value) {
        this.noZWrite = value;
    }

    /**
     * Gets the value of the noZTest property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoZTest }
     *     
     */
    public CtNoZTest getNoZTest() {
        return noZTest;
    }

    /**
     * Sets the value of the noZTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoZTest }
     *     
     */
    public void setNoZTest(CtNoZTest value) {
        this.noZTest = value;
    }

    /**
     * Gets the value of the hideOnTIN property.
     * 
     * @return
     *     possible object is
     *     {@link CtHideOnTIN }
     *     
     */
    public CtHideOnTIN getHideOnTIN() {
        return hideOnTIN;
    }

    /**
     * Sets the value of the hideOnTIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtHideOnTIN }
     *     
     */
    public void setHideOnTIN(CtHideOnTIN value) {
        this.hideOnTIN = value;
    }

    /**
     * Gets the value of the noSnow property.
     * 
     * @return
     *     possible object is
     *     {@link CtNoSnow }
     *     
     */
    public CtNoSnow getNoSnow() {
        return noSnow;
    }

    /**
     * Sets the value of the noSnow property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNoSnow }
     *     
     */
    public void setNoSnow(CtNoSnow value) {
        this.noSnow = value;
    }

    /**
     * Gets the value of the beacon property.
     * 
     * @return
     *     possible object is
     *     {@link CtBeacon }
     *     
     */
    public CtBeacon getBeacon() {
        return beacon;
    }

    /**
     * Sets the value of the beacon property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBeacon }
     *     
     */
    public void setBeacon(CtBeacon value) {
        this.beacon = value;
    }

    /**
     * Gets the value of the effect property.
     * 
     * @return
     *     possible object is
     *     {@link CtEffect }
     *     
     */
    public CtEffect getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtEffect }
     *     
     */
    public void setEffect(CtEffect value) {
        this.effect = value;
    }

    /**
     * Gets the value of the genericBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link CtGenericBuilding }
     *     
     */
    public CtGenericBuilding getGenericBuilding() {
        return genericBuilding;
    }

    /**
     * Sets the value of the genericBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtGenericBuilding }
     *     
     */
    public void setGenericBuilding(CtGenericBuilding value) {
        this.genericBuilding = value;
    }

    /**
     * Gets the value of the libraryObject property.
     * 
     * @return
     *     possible object is
     *     {@link CtLibraryObject }
     *     
     */
    public CtLibraryObject getLibraryObject() {
        return libraryObject;
    }

    /**
     * Sets the value of the libraryObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtLibraryObject }
     *     
     */
    public void setLibraryObject(CtLibraryObject value) {
        this.libraryObject = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link CtTrigger }
     *     
     */
    public CtTrigger getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtTrigger }
     *     
     */
    public void setTrigger(CtTrigger value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the windsock property.
     * 
     * @return
     *     possible object is
     *     {@link CtWindsock }
     *     
     */
    public CtWindsock getWindsock() {
        return windsock;
    }

    /**
     * Sets the value of the windsock property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtWindsock }
     *     
     */
    public void setWindsock(CtWindsock value) {
        this.windsock = value;
    }

    /**
     * Gets the value of the simObject property.
     * 
     * @return
     *     possible object is
     *     {@link CtSimObject }
     *     
     */
    public CtSimObject getSimObject() {
        return simObject;
    }

    /**
     * Sets the value of the simObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtSimObject }
     *     
     */
    public void setSimObject(CtSimObject value) {
        this.simObject = value;
    }

    /**
     * Gets the value of the worldScript property.
     * 
     * @return
     *     possible object is
     *     {@link CtWorldScript }
     *     
     */
    public CtWorldScript getWorldScript() {
        return worldScript;
    }

    /**
     * Sets the value of the worldScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtWorldScript }
     *     
     */
    public void setWorldScript(CtWorldScript value) {
        this.worldScript = value;
    }

    /**
     * Gets the value of the carParking property.
     * 
     * @return
     *     possible object is
     *     {@link CtCarParking }
     *     
     */
    public CtCarParking getCarParking() {
        return carParking;
    }

    /**
     * Sets the value of the carParking property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtCarParking }
     *     
     */
    public void setCarParking(CtCarParking value) {
        this.carParking = value;
    }

    /**
     * Gets the value of the attachedObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachedObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachedObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtAttachedObject }
     * 
     * 
     */
    public List<CtAttachedObject> getAttachedObject() {
        if (attachedObject == null) {
            attachedObject = new ArrayList<CtAttachedObject>();
        }
        return this.attachedObject;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat(String value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLon(Double value) {
        this.lon = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt(String value) {
        this.alt = value;
    }

    /**
     * Gets the value of the altitudeIsAgl property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getAltitudeIsAgl() {
        return altitudeIsAgl;
    }

    /**
     * Sets the value of the altitudeIsAgl property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setAltitudeIsAgl(StBool value) {
        this.altitudeIsAgl = value;
    }

    /**
     * Gets the value of the snapToGround property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getSnapToGround() {
        return snapToGround;
    }

    /**
     * Sets the value of the snapToGround property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setSnapToGround(StBool value) {
        this.snapToGround = value;
    }

    /**
     * Gets the value of the snapToNormal property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getSnapToNormal() {
        return snapToNormal;
    }

    /**
     * Sets the value of the snapToNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setSnapToNormal(StBool value) {
        this.snapToNormal = value;
    }

    /**
     * Gets the value of the pitch property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPitch() {
        return pitch;
    }

    /**
     * Sets the value of the pitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPitch(Double value) {
        this.pitch = value;
    }

    /**
     * Gets the value of the bank property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBank(Double value) {
        this.bank = value;
    }

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeading(Double value) {
        this.heading = value;
    }

    /**
     * Gets the value of the imageComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link StComplexity }
     *     
     */
    public StComplexity getImageComplexity() {
        return imageComplexity;
    }

    /**
     * Sets the value of the imageComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link StComplexity }
     *     
     */
    public void setImageComplexity(StComplexity value) {
        this.imageComplexity = value;
    }

}
