//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctVisualModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctVisualModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BiasXYZ" type="{}ctBias" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="imageComplexity" type="{}stComplexity" />
 *       &lt;attribute name="heading" type="{}stHeading" />
 *       &lt;attribute name="name" use="required" type="{}stGuid" />
 *       &lt;attribute name="instanceId" type="{}stGuid" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctVisualModel", propOrder = {
    "biasXYZ"
})
public class CtVisualModel {

    @XmlElement(name = "BiasXYZ")
    protected CtBias biasXYZ;
    @XmlAttribute(name = "imageComplexity")
    protected StComplexity imageComplexity;
    @XmlAttribute(name = "heading")
    protected Double heading;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "instanceId")
    protected String instanceId;

    /**
     * Gets the value of the biasXYZ property.
     * 
     * @return
     *     possible object is
     *     {@link CtBias }
     *     
     */
    public CtBias getBiasXYZ() {
        return biasXYZ;
    }

    /**
     * Sets the value of the biasXYZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBias }
     *     
     */
    public void setBiasXYZ(CtBias value) {
        this.biasXYZ = value;
    }

    /**
     * Gets the value of the imageComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link StComplexity }
     *     
     */
    public StComplexity getImageComplexity() {
        return imageComplexity;
    }

    /**
     * Sets the value of the imageComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link StComplexity }
     *     
     */
    public void setImageComplexity(StComplexity value) {
        this.imageComplexity = value;
    }

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeading(Double value) {
        this.heading = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }

}
