//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctWindsock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctWindsock">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PoleColor" type="{}ctColor" minOccurs="0"/>
 *         &lt;element name="SockColor" type="{}ctColor" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="poleHeight" type="{}stDistance" />
 *       &lt;attribute name="sockLength" type="{}stDistance" />
 *       &lt;attribute name="lighted" type="{}stBool" />
 *       &lt;attribute name="containerTitle" type="{}stString256" />
 *       &lt;attribute name="containerPath" type="{}stString256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctWindsock", propOrder = {
    "poleColor",
    "sockColor"
})
public class CtWindsock {

    @XmlElement(name = "PoleColor")
    protected CtColor poleColor;
    @XmlElement(name = "SockColor")
    protected CtColor sockColor;
    @XmlAttribute(name = "poleHeight")
    protected String poleHeight;
    @XmlAttribute(name = "sockLength")
    protected String sockLength;
    @XmlAttribute(name = "lighted")
    protected StBool lighted;
    @XmlAttribute(name = "containerTitle")
    protected String containerTitle;
    @XmlAttribute(name = "containerPath")
    protected String containerPath;

    /**
     * Gets the value of the poleColor property.
     * 
     * @return
     *     possible object is
     *     {@link CtColor }
     *     
     */
    public CtColor getPoleColor() {
        return poleColor;
    }

    /**
     * Sets the value of the poleColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtColor }
     *     
     */
    public void setPoleColor(CtColor value) {
        this.poleColor = value;
    }

    /**
     * Gets the value of the sockColor property.
     * 
     * @return
     *     possible object is
     *     {@link CtColor }
     *     
     */
    public CtColor getSockColor() {
        return sockColor;
    }

    /**
     * Sets the value of the sockColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtColor }
     *     
     */
    public void setSockColor(CtColor value) {
        this.sockColor = value;
    }

    /**
     * Gets the value of the poleHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoleHeight() {
        return poleHeight;
    }

    /**
     * Sets the value of the poleHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoleHeight(String value) {
        this.poleHeight = value;
    }

    /**
     * Gets the value of the sockLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSockLength() {
        return sockLength;
    }

    /**
     * Sets the value of the sockLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSockLength(String value) {
        this.sockLength = value;
    }

    /**
     * Gets the value of the lighted property.
     * 
     * @return
     *     possible object is
     *     {@link StBool }
     *     
     */
    public StBool getLighted() {
        return lighted;
    }

    /**
     * Sets the value of the lighted property.
     * 
     * @param value
     *     allowed object is
     *     {@link StBool }
     *     
     */
    public void setLighted(StBool value) {
        this.lighted = value;
    }

    /**
     * Gets the value of the containerTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerTitle() {
        return containerTitle;
    }

    /**
     * Sets the value of the containerTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerTitle(String value) {
        this.containerTitle = value;
    }

    /**
     * Gets the value of the containerPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerPath() {
        return containerPath;
    }

    /**
     * Sets the value of the containerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerPath(String value) {
        this.containerPath = value;
    }

}
