//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stAltitudeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stAltitudeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ABOVE_GROUND_LEVEL"/>
 *     &lt;enumeration value="AGL"/>
 *     &lt;enumeration value="MEAN_SEA_LEVEL"/>
 *     &lt;enumeration value="MSL"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="UNLIMITED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stAltitudeType")
@XmlEnum
public enum StAltitudeType {

    ABOVE_GROUND_LEVEL,
    AGL,
    MEAN_SEA_LEVEL,
    MSL,
    UNKNOWN,
    UNLIMITED;

    public String value() {
        return name();
    }

    public static StAltitudeType fromValue(String v) {
        return valueOf(v);
    }

}
