//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stComType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stComType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="APPROACH"/>
 *     &lt;enumeration value="ASOS"/>
 *     &lt;enumeration value="ATIS"/>
 *     &lt;enumeration value="AWOS"/>
 *     &lt;enumeration value="CENTER"/>
 *     &lt;enumeration value="CLEARANCE"/>
 *     &lt;enumeration value="CLEARANCE_PRE_TAXI"/>
 *     &lt;enumeration value="CTAF"/>
 *     &lt;enumeration value="DEPARTURE"/>
 *     &lt;enumeration value="FSS"/>
 *     &lt;enumeration value="GROUND"/>
 *     &lt;enumeration value="MULTICOM"/>
 *     &lt;enumeration value="REMOTE_CLEARANCE_DELIVERY"/>
 *     &lt;enumeration value="TOWER"/>
 *     &lt;enumeration value="UNICOM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stComType")
@XmlEnum
public enum StComType {

    APPROACH,
    ASOS,
    ATIS,
    AWOS,
    CENTER,
    CLEARANCE,
    CLEARANCE_PRE_TAXI,
    CTAF,
    DEPARTURE,
    FSS,
    GROUND,
    MULTICOM,
    REMOTE_CLEARANCE_DELIVERY,
    TOWER,
    UNICOM;

    public String value() {
        return name();
    }

    public static StComType fromValue(String v) {
        return valueOf(v);
    }

}
