//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stDstEndRule.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stDstEndRule">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DST_RULE_NONE"/>
 *     &lt;enumeration value="DST_RULE_FIXED_DAY"/>
 *     &lt;enumeration value="DST_RULE_LAST_OF_DAY"/>
 *     &lt;enumeration value="DST_RULE_ON_OR_AFTER_DAY"/>
 *     &lt;enumeration value="DST_RULE_ON_OR_BEFORE_DAY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stDstEndRule")
@XmlEnum
public enum StDstEndRule {

    DST_RULE_NONE,
    DST_RULE_FIXED_DAY,
    DST_RULE_LAST_OF_DAY,
    DST_RULE_ON_OR_AFTER_DAY,
    DST_RULE_ON_OR_BEFORE_DAY;

    public String value() {
        return name();
    }

    public static StDstEndRule fromValue(String v) {
        return valueOf(v);
    }

}
