//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stFixType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stFixType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NDB"/>
 *     &lt;enumeration value="TERMINAL_NDB"/>
 *     &lt;enumeration value="TERMINAL_WAYPOINT"/>
 *     &lt;enumeration value="VOR"/>
 *     &lt;enumeration value="WAYPOINT"/>
 *     &lt;enumeration value="RUNWAY"/>
 *     &lt;enumeration value="LOCALIZER"/>
 *     &lt;enumeration value="AIRPORT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stFixType")
@XmlEnum
public enum StFixType {

    NDB,
    TERMINAL_NDB,
    TERMINAL_WAYPOINT,
    VOR,
    WAYPOINT,
    RUNWAY,
    LOCALIZER,
    AIRPORT;

    public String value() {
        return name();
    }

    public static StFixType fromValue(String v) {
        return valueOf(v);
    }

}
