//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stLegType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stLegType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CD"/>
 *     &lt;enumeration value="CF"/>
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="DF"/>
 *     &lt;enumeration value="FA"/>
 *     &lt;enumeration value="FC"/>
 *     &lt;enumeration value="FD"/>
 *     &lt;enumeration value="FM"/>
 *     &lt;enumeration value="HA"/>
 *     &lt;enumeration value="HF"/>
 *     &lt;enumeration value="HM"/>
 *     &lt;enumeration value="IF"/>
 *     &lt;enumeration value="PI"/>
 *     &lt;enumeration value="RF"/>
 *     &lt;enumeration value="TF"/>
 *     &lt;enumeration value="VA"/>
 *     &lt;enumeration value="VD"/>
 *     &lt;enumeration value="VI"/>
 *     &lt;enumeration value="VM"/>
 *     &lt;enumeration value="VR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stLegType")
@XmlEnum
public enum StLegType {

    AF,
    CA,
    CD,
    CF,
    CI,
    CR,
    DF,
    FA,
    FC,
    FD,
    FM,
    HA,
    HF,
    HM,
    IF,
    PI,
    RF,
    TF,
    VA,
    VD,
    VI,
    VM,
    VR;

    public String value() {
        return name();
    }

    public static StLegType fromValue(String v) {
        return valueOf(v);
    }

}
