//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 10:27:20 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stPaintedLineTrueAngle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stPaintedLineTrueAngle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="BEGIN"/>
 *     &lt;enumeration value="END"/>
 *     &lt;enumeration value="BOTH_ENDS"/>
 *     &lt;enumeration value="ALL_POINTS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stPaintedLineTrueAngle")
@XmlEnum
public enum StPaintedLineTrueAngle {

    NONE,
    BEGIN,
    END,
    BOTH_ENDS,
    ALL_POINTS;

    public String value() {
        return name();
    }

    public static StPaintedLineTrueAngle fromValue(String v) {
        return valueOf(v);
    }

}
