//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 05:00:27 PM CEST 
//


package generatedXmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stPaintedLineType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stPaintedLineType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DEFAULT"/>
 *     &lt;enumeration value="HOLD_SHORT_FORWARD"/>
 *     &lt;enumeration value="HOLD_SHORT_BACKWARD"/>
 *     &lt;enumeration value="HOLD_SHORT_FORWARD_MARKED"/>
 *     &lt;enumeration value="HOLD_SHORT_BACKWARD_MARKED"/>
 *     &lt;enumeration value="ILS_HOLD_SHORT"/>
 *     &lt;enumeration value="EDGE_LINE_SOLID"/>
 *     &lt;enumeration value="EDGE_LINE_DASHED"/>
 *     &lt;enumeration value="HOLD_SHORT_TAXIWAY"/>
 *     &lt;enumeration value="SERVICE_DASHED"/>
 *     &lt;enumeration value="EDGE_SERVICE_SOLID"/>
 *     &lt;enumeration value="EDGE_SERVICE_DASHED"/>
 *     &lt;enumeration value="WIDE_YELLOW"/>
 *     &lt;enumeration value="WIDE_WHITE"/>
 *     &lt;enumeration value="WIDE_RED"/>
 *     &lt;enumeration value="SLIM_RED"/>
 *     &lt;enumeration value="EDGE_SOLID_ORTHO"/>
 *     &lt;enumeration value="EDGE_SOLID_ORTHO_BACK"/>
 *     &lt;enumeration value="NON_MOVEMENT"/>
 *     &lt;enumeration value="NON_MOVEMENT_BACK"/>
 *     &lt;enumeration value="ENHANCED_CENTER"/>
 *     &lt;enumeration value="DEFAULT_LIGHTED"/>
 *     &lt;enumeration value="HOLD_SHORT_FORWARD_MARKED_L"/>
 *     &lt;enumeration value="HOLD_SHORT_BACKWARD_MARKED_L"/>
 *     &lt;enumeration value="HOLD_SHORT_FORWARD_LIGHTED"/>
 *     &lt;enumeration value="HOLD_SHORT_BACKWARD_LIGHTED"/>
 *     &lt;enumeration value="ILS_HOLD_SHORT_LIGHTED"/>
 *     &lt;enumeration value="EDGE_LINE_SOLID_LIGHTED"/>
 *     &lt;enumeration value="EDGE_LINE_DASHED_LIGHTED"/>
 *     &lt;enumeration value="HOLD_SHORT_TAXIWAY_LIGHTED"/>
 *     &lt;enumeration value="SERVICE_DASHED_LIGHTED"/>
 *     &lt;enumeration value="EDGE_SERVICE_SOLID_LIGHTED"/>
 *     &lt;enumeration value="EDGE_SERVICE_DASHED_LIGHTED"/>
 *     &lt;enumeration value="WIDE_YELLOW_LIGHTED"/>
 *     &lt;enumeration value="WIDE_WHITE_LIGHTED"/>
 *     &lt;enumeration value="WIDE_RED_LIGHTED"/>
 *     &lt;enumeration value="SLIM_RED_LIGHTED"/>
 *     &lt;enumeration value="EDGE_SOLID_ORTHO_LIGHTED"/>
 *     &lt;enumeration value="EDGE_SOLID_ORTHO_BACK_LIGHT"/>
 *     &lt;enumeration value="NON_MOVEMENT_LIGHTED"/>
 *     &lt;enumeration value="NON_MOVEMENT_BACK_LIGHTED"/>
 *     &lt;enumeration value="ENHANCED_CENTER_LIGHTED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stPaintedLineType")
@XmlEnum
public enum StPaintedLineType {

    DEFAULT,
    HOLD_SHORT_FORWARD,
    HOLD_SHORT_BACKWARD,
    HOLD_SHORT_FORWARD_MARKED,
    HOLD_SHORT_BACKWARD_MARKED,
    ILS_HOLD_SHORT,
    EDGE_LINE_SOLID,
    EDGE_LINE_DASHED,
    HOLD_SHORT_TAXIWAY,
    SERVICE_DASHED,
    EDGE_SERVICE_SOLID,
    EDGE_SERVICE_DASHED,
    WIDE_YELLOW,
    WIDE_WHITE,
    WIDE_RED,
    SLIM_RED,
    EDGE_SOLID_ORTHO,
    EDGE_SOLID_ORTHO_BACK,
    NON_MOVEMENT,
    NON_MOVEMENT_BACK,
    ENHANCED_CENTER,
    DEFAULT_LIGHTED,
    HOLD_SHORT_FORWARD_MARKED_L,
    HOLD_SHORT_BACKWARD_MARKED_L,
    HOLD_SHORT_FORWARD_LIGHTED,
    HOLD_SHORT_BACKWARD_LIGHTED,
    ILS_HOLD_SHORT_LIGHTED,
    EDGE_LINE_SOLID_LIGHTED,
    EDGE_LINE_DASHED_LIGHTED,
    HOLD_SHORT_TAXIWAY_LIGHTED,
    SERVICE_DASHED_LIGHTED,
    EDGE_SERVICE_SOLID_LIGHTED,
    EDGE_SERVICE_DASHED_LIGHTED,
    WIDE_YELLOW_LIGHTED,
    WIDE_WHITE_LIGHTED,
    WIDE_RED_LIGHTED,
    SLIM_RED_LIGHTED,
    EDGE_SOLID_ORTHO_LIGHTED,
    EDGE_SOLID_ORTHO_BACK_LIGHT,
    NON_MOVEMENT_LIGHTED,
    NON_MOVEMENT_BACK_LIGHTED,
    ENHANCED_CENTER_LIGHTED;

    public String value() {
        return name();
    }

    public static StPaintedLineType fromValue(String v) {
        return valueOf(v);
    }

}
